library(testthat)
library(mfp2)


test_that("MFPI duplicate display labels receive closed unique suffixes", {
  labels <- rep("treatment [Yes]", 12L)

  out <- mfp2:::mfpi_make_unique_display_names(labels)

  # The first display label is preserved. Later occurrences receive the numeric
  # suffix generated by make.unique(), completed with a closing bracket.
  expect_identical(out[[1L]], "treatment [Yes]")
  expect_identical(out[[2L]], "treatment [Yes] [1]")
  expect_identical(out[[12L]], "treatment [Yes] [11]")
  expect_identical(anyDuplicated(out), 0L)

  # No generated label may retain make.unique()'s intentionally open suffix.
  expect_false(any(grepl(" \\[[0-9]+$", out)))
})


test_that("MFPI display-name de-duplication preserves unaffected labels", {
  unique_labels <- c("(Intercept)", "treatment [Yes]", "Control: log(x)")
  expect_identical(
    mfp2:::mfpi_make_unique_display_names(unique_labels),
    unique_labels
  )

  labels <- c("age", "age", "size", "age")
  expect_identical(
    mfp2:::mfpi_make_unique_display_names(labels),
    c("age", "age [1]", "size", "age [2]")
  )
})
