// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// transform_fp_core
NumericMatrix transform_fp_core(NumericVector x_raw, NumericVector power, double shift_val, double scale_val, bool zero);
RcppExport SEXP _mfp2_transform_fp_core(SEXP x_rawSEXP, SEXP powerSEXP, SEXP shift_valSEXP, SEXP scale_valSEXP, SEXP zeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_raw(x_rawSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type power(powerSEXP);
    Rcpp::traits::input_parameter< double >::type shift_val(shift_valSEXP);
    Rcpp::traits::input_parameter< double >::type scale_val(scale_valSEXP);
    Rcpp::traits::input_parameter< bool >::type zero(zeroSEXP);
    rcpp_result_gen = Rcpp::wrap(transform_fp_core(x_raw, power, shift_val, scale_val, zero));
    return rcpp_result_gen;
END_RCPP
}
// generate_transformations_fp_cpp
List generate_transformations_fp_cpp(const NumericVector& x, const NumericMatrix& powers, const bool zero, Nullable<NumericMatrix> catzero);
RcppExport SEXP _mfp2_generate_transformations_fp_cpp(SEXP xSEXP, SEXP powersSEXP, SEXP zeroSEXP, SEXP catzeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type powers(powersSEXP);
    Rcpp::traits::input_parameter< const bool >::type zero(zeroSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type catzero(catzeroSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_transformations_fp_cpp(x, powers, zero, catzero));
    return rcpp_result_gen;
END_RCPP
}
// generate_transformations_fp_basis_cpp
List generate_transformations_fp_basis_cpp(const NumericVector& x, const NumericMatrix& powers, const bool zero);
RcppExport SEXP _mfp2_generate_transformations_fp_basis_cpp(SEXP xSEXP, SEXP powersSEXP, SEXP zeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type powers(powersSEXP);
    Rcpp::traits::input_parameter< const bool >::type zero(zeroSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_transformations_fp_basis_cpp(x, powers, zero));
    return rcpp_result_gen;
END_RCPP
}
// copy_fp_basis_candidate_cpp
NumericMatrix copy_fp_basis_candidate_cpp(NumericMatrix target, const NumericMatrix& basis, const IntegerVector& source_cols, const IntegerVector& target_cols);
RcppExport SEXP _mfp2_copy_fp_basis_candidate_cpp(SEXP targetSEXP, SEXP basisSEXP, SEXP source_colsSEXP, SEXP target_colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type basis(basisSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type source_cols(source_colsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type target_cols(target_colsSEXP);
    rcpp_result_gen = Rcpp::wrap(copy_fp_basis_candidate_cpp(target, basis, source_cols, target_cols));
    return rcpp_result_gen;
END_RCPP
}
// fill_mfpi_fp_candidate_cpp
List fill_mfpi_fp_candidate_cpp(NumericMatrix target, const NumericMatrix& basis, const IntegerVector& source_cols, const IntegerVector& group_idx, const int n_groups, const int target_start_col, const bool center, const bool group_center, const LogicalVector& valid_rows);
RcppExport SEXP _mfp2_fill_mfpi_fp_candidate_cpp(SEXP targetSEXP, SEXP basisSEXP, SEXP source_colsSEXP, SEXP group_idxSEXP, SEXP n_groupsSEXP, SEXP target_start_colSEXP, SEXP centerSEXP, SEXP group_centerSEXP, SEXP valid_rowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type basis(basisSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type source_cols(source_colsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type group_idx(group_idxSEXP);
    Rcpp::traits::input_parameter< const int >::type n_groups(n_groupsSEXP);
    Rcpp::traits::input_parameter< const int >::type target_start_col(target_start_colSEXP);
    Rcpp::traits::input_parameter< const bool >::type center(centerSEXP);
    Rcpp::traits::input_parameter< const bool >::type group_center(group_centerSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type valid_rows(valid_rowsSEXP);
    rcpp_result_gen = Rcpp::wrap(fill_mfpi_fp_candidate_cpp(target, basis, source_cols, group_idx, n_groups, target_start_col, center, group_center, valid_rows));
    return rcpp_result_gen;
END_RCPP
}
// build_adjustment_step_loop_cpp
List build_adjustment_step_loop_cpp(const NumericMatrix& x, const IntegerVector& x_col_index, const CharacterVector& vars_adj, const List& powers_adj, const LogicalVector& acdx_adj, const LogicalVector& zero_adj, const List& catzero_adj, const LogicalVector& spike_adj, const IntegerVector& spike_decision_int_adj, const List& acd_parameter_adj, const LogicalVector& eliminated, const LogicalVector& spike_binary_only_flags, const List& current_power_keys_adj, const List& prev_power_keys_adj, const List& prev_data_adj_list, const IntegerVector& prev_spike_decision_int_adj, const bool has_prev);
RcppExport SEXP _mfp2_build_adjustment_step_loop_cpp(SEXP xSEXP, SEXP x_col_indexSEXP, SEXP vars_adjSEXP, SEXP powers_adjSEXP, SEXP acdx_adjSEXP, SEXP zero_adjSEXP, SEXP catzero_adjSEXP, SEXP spike_adjSEXP, SEXP spike_decision_int_adjSEXP, SEXP acd_parameter_adjSEXP, SEXP eliminatedSEXP, SEXP spike_binary_only_flagsSEXP, SEXP current_power_keys_adjSEXP, SEXP prev_power_keys_adjSEXP, SEXP prev_data_adj_listSEXP, SEXP prev_spike_decision_int_adjSEXP, SEXP has_prevSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type x_col_index(x_col_indexSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type vars_adj(vars_adjSEXP);
    Rcpp::traits::input_parameter< const List& >::type powers_adj(powers_adjSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type acdx_adj(acdx_adjSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type zero_adj(zero_adjSEXP);
    Rcpp::traits::input_parameter< const List& >::type catzero_adj(catzero_adjSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type spike_adj(spike_adjSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type spike_decision_int_adj(spike_decision_int_adjSEXP);
    Rcpp::traits::input_parameter< const List& >::type acd_parameter_adj(acd_parameter_adjSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type eliminated(eliminatedSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type spike_binary_only_flags(spike_binary_only_flagsSEXP);
    Rcpp::traits::input_parameter< const List& >::type current_power_keys_adj(current_power_keys_adjSEXP);
    Rcpp::traits::input_parameter< const List& >::type prev_power_keys_adj(prev_power_keys_adjSEXP);
    Rcpp::traits::input_parameter< const List& >::type prev_data_adj_list(prev_data_adj_listSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type prev_spike_decision_int_adj(prev_spike_decision_int_adjSEXP);
    Rcpp::traits::input_parameter< const bool >::type has_prev(has_prevSEXP);
    rcpp_result_gen = Rcpp::wrap(build_adjustment_step_loop_cpp(x, x_col_index, vars_adj, powers_adj, acdx_adj, zero_adj, catzero_adj, spike_adj, spike_decision_int_adj, acd_parameter_adj, eliminated, spike_binary_only_flags, current_power_keys_adj, prev_power_keys_adj, prev_data_adj_list, prev_spike_decision_int_adj, has_prev));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mfp2_transform_fp_core", (DL_FUNC) &_mfp2_transform_fp_core, 5},
    {"_mfp2_generate_transformations_fp_cpp", (DL_FUNC) &_mfp2_generate_transformations_fp_cpp, 4},
    {"_mfp2_generate_transformations_fp_basis_cpp", (DL_FUNC) &_mfp2_generate_transformations_fp_basis_cpp, 3},
    {"_mfp2_copy_fp_basis_candidate_cpp", (DL_FUNC) &_mfp2_copy_fp_basis_candidate_cpp, 4},
    {"_mfp2_fill_mfpi_fp_candidate_cpp", (DL_FUNC) &_mfp2_fill_mfpi_fp_candidate_cpp, 9},
    {"_mfp2_build_adjustment_step_loop_cpp", (DL_FUNC) &_mfp2_build_adjustment_step_loop_cpp, 17},
    {NULL, NULL, 0}
};

RcppExport void R_init_mfp2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
