// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// transform_fp_core
NumericMatrix transform_fp_core(NumericVector x_raw, NumericVector power, double shift_val, double scale_val, bool zero);
RcppExport SEXP _mfp2_transform_fp_core(SEXP x_rawSEXP, SEXP powerSEXP, SEXP shift_valSEXP, SEXP scale_valSEXP, SEXP zeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_raw(x_rawSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type power(powerSEXP);
    Rcpp::traits::input_parameter< double >::type shift_val(shift_valSEXP);
    Rcpp::traits::input_parameter< double >::type scale_val(scale_valSEXP);
    Rcpp::traits::input_parameter< bool >::type zero(zeroSEXP);
    rcpp_result_gen = Rcpp::wrap(transform_fp_core(x_raw, power, shift_val, scale_val, zero));
    return rcpp_result_gen;
END_RCPP
}
// generate_transformations_fp_cpp
List generate_transformations_fp_cpp(const NumericVector& x, const NumericMatrix& powers, const bool zero, Nullable<NumericMatrix> catzero);
RcppExport SEXP _mfp2_generate_transformations_fp_cpp(SEXP xSEXP, SEXP powersSEXP, SEXP zeroSEXP, SEXP catzeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type powers(powersSEXP);
    Rcpp::traits::input_parameter< const bool >::type zero(zeroSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type catzero(catzeroSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_transformations_fp_cpp(x, powers, zero, catzero));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mfp2_transform_fp_core", (DL_FUNC) &_mfp2_transform_fp_core, 5},
    {"_mfp2_generate_transformations_fp_cpp", (DL_FUNC) &_mfp2_generate_transformations_fp_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_mfp2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
