# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

transform_fp_core <- function(x_raw, power, shift_val, scale_val, zero) {
    .Call(`_mfp2_transform_fp_core`, x_raw, power, shift_val, scale_val, zero)
}

